window_padding_width 4
include flexoki_dark.conf


# BEGIN_KITTY_FONTS
font_family      family="Monaspace Neon"
bold_font        family="Monaspace Xenon"
italic_font      family="Monaspace Radon"
bold_italic_font family="Monaspace Xenon"
# END_KITTY_FONTS
